# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'att.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(870, 489)
        self.img_dir_att = QtWidgets.QLabel(Form)
        self.img_dir_att.setGeometry(QtCore.QRect(40, 110, 701, 61))
        self.img_dir_att.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.img_dir_att.setFrameShadow(QtWidgets.QFrame.Plain)
        self.img_dir_att.setText("")
        self.img_dir_att.setObjectName("img_dir_att")
        self.label_dir_att = QtWidgets.QLabel(Form)
        self.label_dir_att.setGeometry(QtCore.QRect(40, 40, 701, 61))
        self.label_dir_att.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_dir_att.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_dir_att.setText("")
        self.label_dir_att.setObjectName("label_dir_att")
        self.save_dir_att = QtWidgets.QLabel(Form)
        self.save_dir_att.setGeometry(QtCore.QRect(40, 180, 701, 61))
        self.save_dir_att.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.save_dir_att.setFrameShadow(QtWidgets.QFrame.Plain)
        self.save_dir_att.setText("")
        self.save_dir_att.setObjectName("save_dir_att")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 260, 651, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.confirm = QtWidgets.QPushButton(Form)
        self.confirm.setGeometry(QtCore.QRect(110, 350, 111, 41))
        self.confirm.setObjectName("confirm")
        self.dont = QtWidgets.QPushButton(Form)
        self.dont.setGeometry(QtCore.QRect(280, 350, 111, 41))
        self.dont.setObjectName("dont")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "执行后无法撤销，确定执行？"))
        self.confirm.setText(_translate("Form", "确定"))
        self.dont.setText(_translate("Form", "取消"))
